// Slide Types
export const FETCH_SLIDES_REQUEST = 'FETCH_SLIDES_REQUEST';
export const FETCH_SLIDES_SUCCESS = 'FETCH_SLIDES_SUCCESS';
export const FETCH_SLIDES_FAILURE = 'FETCH_SLIDES_FAILURE';
export const CREATE_SLIDE_REQUEST = 'CREATE_SLIDE_REQUEST';
export const CREATE_SLIDE_SUCCESS = 'CREATE_SLIDE_SUCCESS';
export const CREATE_SLIDE_FAILURE = 'CREATE_SLIDE_FAILURE';
export const UPDATE_SLIDE_REQUEST = 'UPDATE_SLIDE_REQUEST';
export const UPDATE_SLIDE_SUCCESS = 'UPDATE_SLIDE_SUCCESS';
export const UPDATE_SLIDE_FAILURE = 'UPDATE_SLIDE_FAILURE';
export const DELETE_SLIDE_REQUEST = 'DELETE_SLIDE_REQUEST';
export const DELETE_SLIDE_SUCCESS = 'DELETE_SLIDE_SUCCESS';
export const DELETE_SLIDE_FAILURE = 'DELETE_SLIDE_FAILURE';