// Well Types
export const FETCH_WELLS_REQUEST = 'FETCH_WELLS_REQUEST';
export const FETCH_WELLS_SUCCESS = 'FETCH_WELLS_SUCCESS';
export const FETCH_WELLS_FAILURE = 'FETCH_WELLS_FAILURE';
export const CREATE_WELL_REQUEST = 'CREATE_WELL_REQUEST';
export const CREATE_WELL_SUCCESS = 'CREATE_WELL_SUCCESS';
export const CREATE_WELL_FAILURE = 'CREATE_WELL_FAILURE';
export const UPDATE_WELL_REQUEST = 'UPDATE_WELL_REQUEST';
export const UPDATE_WELL_SUCCESS = 'UPDATE_WELL_SUCCESS';
export const UPDATE_WELL_FAILURE = 'UPDATE_WELL_FAILURE';
export const DELETE_WELL_REQUEST = 'DELETE_WELL_REQUEST';
export const DELETE_WELL_SUCCESS = 'DELETE_WELL_SUCCESS';
export const DELETE_WELL_FAILURE = 'DELETE_WELL_FAILURE';