// Tyend Types
export const FETCH_TYENDS_REQUEST = 'FETCH_TYENDS_REQUEST';
export const FETCH_TYENDS_SUCCESS = 'FETCH_TYENDS_SUCCESS';
export const FETCH_TYENDS_FAILURE = 'FETCH_TYENDS_FAILURE';
export const CREATE_TYEND_REQUEST = 'CREATE_TYEND_REQUEST';
export const CREATE_TYEND_SUCCESS = 'CREATE_TYEND_SUCCESS';
export const CREATE_TYEND_FAILURE = 'CREATE_TYEND_FAILURE';
export const UPDATE_TYEND_REQUEST = 'UPDATE_TYEND_REQUEST';
export const UPDATE_TYEND_SUCCESS = 'UPDATE_TYEND_SUCCESS';
export const UPDATE_TYEND_FAILURE = 'UPDATE_TYEND_FAILURE';
export const DELETE_TYEND_REQUEST = 'DELETE_TYEND_REQUEST';
export const DELETE_TYEND_SUCCESS = 'DELETE_TYEND_SUCCESS';
export const DELETE_TYEND_FAILURE = 'DELETE_TYEND_FAILURE';